site_name: Human Phenotype Ontology to Google Forms
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
plugins:
  - search
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - attr_list
  - md_in_html
  - tables
#site_url: https://obophenotype.github.io/human-phenotype-ontology/
#repo_url: https://github.com/obophenotype/human-phenotype-ontology/


nav:
  - Home: 'index.md'
  - Running:
      - Java: 'hpo2gforms.md'
      - gapps: "gapps.md"
      - distribution: "distribution.md"
      - evaluation: "evaluation.md"
  - Developers:
      - Documentation: 'documentation.md'
